In [75]:
import time

import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.cluster import MiniBatchKMeans, KMeans
from sklearn.metrics.pairwise import pairwise_distances_argmin
from sklearn.datasets.samples_generator import make_blobs

In [89]:
C = [[1, 2], [4, 5]]


test = [(i, x) for (i, x) in enumerate(C)]
test

[(0, [1, 2]), (1, [4, 5])]

In [77]:
np.array(C)

array([[1, 2],
       [4, 5]])

In [78]:
X = np.array([[1, 2], [1, 4], [1, 0], [4, 3], [7, 4],
              [4, 2], [4, 4], [4, 0], [10, 5]])

In [79]:
X

array([[ 1,  2],
       [ 1,  4],
       [ 1,  0],
       [ 4,  3],
       [ 7,  4],
       [ 4,  2],
       [ 4,  4],
       [ 4,  0],
       [10,  5]])

In [80]:
np.append(X, [[2, 100]])

array([  1,   2,   1,   4,   1,   0,   4,   3,   7,   4,   4,   2,   4,
         4,   4,   0,  10,   5,   2, 100])

In [81]:
kmeans = MiniBatchKMeans(n_clusters=2, random_state=0)

In [84]:
if hasattr(kmeans, "cluster_centers_"):
    kmeans.cluster_centers_
    print("OLA")

OLA


In [83]:
kmeans.partial_fit(X)

MiniBatchKMeans(batch_size=100, compute_labels=True, init='k-means++',
        init_size=None, max_iter=100, max_no_improvement=10, n_clusters=2,
        n_init=3, random_state=0, reassignment_ratio=0.01, tol=0.0,
        verbose=0)

In [42]:
kmeans.cluster_centers_

array([[2, 2],
       [8, 4]])

In [44]:
kmeans.cluster_centers_[0][0]

2

In [9]:
kmeans.partial_fit([[1,1]])

MiniBatchKMeans(batch_size=100, compute_labels=True, init='k-means++',
        init_size=None, max_iter=100, max_no_improvement=10, n_clusters=2,
        n_init=3, random_state=0, reassignment_ratio=0.01, tol=0.0,
        verbose=0)

In [10]:
kmeans.cluster_centers_

array([[1, 1],
       [8, 4]])

In [12]:
kmeans.partial_fit([[3,3]])

MiniBatchKMeans(batch_size=100, compute_labels=True, init='k-means++',
        init_size=None, max_iter=100, max_no_improvement=10, n_clusters=2,
        n_init=3, random_state=0, reassignment_ratio=0.01, tol=0.0,
        verbose=0)

In [13]:
kmeans.cluster_centers_

array([[1, 1],
       [8, 4]])

In [14]:
kmeans.partial_fit([[3,3]])


MiniBatchKMeans(batch_size=100, compute_labels=True, init='k-means++',
        init_size=None, max_iter=100, max_no_improvement=10, n_clusters=2,
        n_init=3, random_state=0, reassignment_ratio=0.01, tol=0.0,
        verbose=0)

In [15]:
kmeans.cluster_centers_

array([[1, 1],
       [8, 4]])

In [16]:
kmeans.partial_fit([[3,3]])


MiniBatchKMeans(batch_size=100, compute_labels=True, init='k-means++',
        init_size=None, max_iter=100, max_no_improvement=10, n_clusters=2,
        n_init=3, random_state=0, reassignment_ratio=0.01, tol=0.0,
        verbose=0)

In [17]:
kmeans.cluster_centers_

array([[1, 1],
       [8, 4]])

In [18]:
kmeans.partial_fit([[3,3]])
kmeans.cluster_centers_

array([[1, 1],
       [8, 4]])

In [19]:
kmeans.partial_fit([[3,3]])
kmeans.cluster_centers_

array([[1, 1],
       [8, 4]])

In [20]:
kmeans.partial_fit([[3,3]])
kmeans.cluster_centers_

array([[1, 1],
       [8, 4]])

In [21]:
kmeans.partial_fit([[3,3]])
kmeans.cluster_centers_

array([[1, 1],
       [8, 4]])

In [22]:
kmeans.partial_fit([[3,3]])
kmeans.cluster_centers_

array([[1, 1],
       [8, 4]])

In [23]:
kmeans.partial_fit([[3,3]])
kmeans.cluster_centers_

array([[1, 1],
       [8, 4]])

In [24]:
kmeans.partial_fit([[3,3]])
kmeans.cluster_centers_

array([[1, 1],
       [8, 4]])

In [25]:
kmeans.partial_fit([[3,3]])
kmeans.cluster_centers_

array([[1, 1],
       [8, 4]])

In [26]:
kmeans.partial_fit([[3,3]])
kmeans.cluster_centers_

array([[1, 1],
       [8, 4]])

In [27]:
kmeans.partial_fit([[3,3]])
kmeans.cluster_centers_

array([[1, 1],
       [8, 4]])

In [30]:
kmeans.partial_fit([[3,3]])
kmeans.cluster_centers_

array([[1, 1],
       [8, 4]])

In [31]:
kmeans.partial_fit([[3,3]])
kmeans.cluster_centers_

array([[1, 1],
       [8, 4]])

In [32]:
kmeans.partial_fit([[3,3]])
kmeans.cluster_centers_

array([[1, 1],
       [8, 4]])

In [33]:
kmeans.partial_fit([[3,3]])
kmeans.cluster_centers_

array([[1, 1],
       [8, 4]])

In [34]:
kmeans.partial_fit([[3,3]])
kmeans.cluster_centers_

array([[1, 1],
       [8, 4]])

In [35]:
kmeans.partial_fit([[3,3]])
kmeans.cluster_centers_

array([[1, 1],
       [8, 4]])

In [36]:
kmeans.partial_fit([[3,3]])
kmeans.cluster_centers_

array([[1, 1],
       [8, 4]])

In [37]:
kmeans.partial_fit([[3,3]])
kmeans.cluster_centers_

array([[1, 1],
       [8, 4]])

In [38]:
kmeans.partial_fit([[3,3]])
kmeans.cluster_centers_

array([[1, 1],
       [8, 4]])

In [39]:
kmeans.partial_fit([[3,3]])
kmeans.cluster_centers_

array([[1, 1],
       [8, 4]])

In [40]:
kmeans.partial_fit([[100,100]])
kmeans.cluster_centers_

array([[ 1,  1],
       [38, 36]])

In [41]:
kmeans.partial_fit([[-200,20]])
kmeans.cluster_centers_

array([[-5,  1],
       [38, 36]])